chat-format:
  enabled: false

  # Where we should get the permissions from.
  # A general API like Vault will be best, but some other concrete implementations or a better (less popular) API may provide better performance in **some** case senarios.
  # The current list:
  # - LuckPerms
  # - Vault (Recommended)
  #
  # If you don't know what to choose, keep this at its current choice.
  chat-provider: "Vault"

chat-cooldown:
  enabled: false

  # Order matters, whatever comes first in the list gets done first
  # How to use every default actions:
  #
  # Sound:
  # SOUND:<SoundType>:<Volume>:<Pitch>
  #
  # Action-bar:
  # ACTION_BAR:<Message>:[papi]
  #
  # Title:
  # TITLE:<Title>:<Subtitle>:<FadeIn>:<FadeOut>:<Stay>
  # The durations are in milliseconds, 1000 milliseconds equals 1 second :D
  on-chat-cooldown-actions:
    - "SOUND:UI_BUTTON_CLICK:1:1"
    - "ACTION_BAR:<gray>You are on cooldown!"

  # In seconds, may use decimals as milliseconds
  cooldown: 10

mentions:
  enabled: false

  # How to start a mention, such as @FlameyosFlow, #FlameyosFlow. if you don't want a mention symbol leave it blank at ""
  mention-symbol: ""
  mention-color: GREEN

  # Order matters, whatever comes first in the list gets done first
  # How to use every default actions:
  #
  # Sound:
  # SOUND:<SoundType>:<Volume>:<Pitch>
  #
  # Action-bar:
  # ACTION_BAR:<Message>:[papi]
  #
  # Title:
  # TITLE:<Title>:<Subtitle>:<FadeIn>:<FadeOut>:<Stay>
  # The durations are in milliseconds, 1000 milliseconds equals 1 second :D
  on-mention-actions:
    - "SOUND:UI_BUTTON_CLICK:1:1"
    - "ACTION_BAR:<gray>You got mentioned by <bold><red>%player%"
    - "TITLE:<gray>You got mentioned by <bold><red>%player% (Title):Respond to Him (Subtitle):1:1:1"

# If you enable this or disable this, please restart the server for full stability :D
messaging:
  enabled: false

  count-message-other-as-conversation-end: true

  message-sender-format: "<gray>[<light_gray>You <gray>-> <light_gray>%recipient%<gray>]<light_gray>: <reset>%message%"

  message-recipient-format: "<gray>[<light_gray>%sender% <gray>-> <light_gray>You<gray>]<light_gray>: <reset>%message%"

# Do not touch under any circumstances, this config file will be reset, and you will lose all the current edits you have made on this file.
# This is auto generated by BoostedYAML.
config-version: 1