# Group formats:
# Empty (No chat formatter)
# - {world} - Displays the world name
# - {displayname} - Displays the user's display name (in MiniMessage formatting)
# - {name} - Displays the user's real name.
# - {message} - Displays the message that the user have sent
#
# Luckperms, Vault (Permissions-based/ranks-based chat formatting, includes empty chat formatting)
# -
chat-format:
  # Where we should get the permissions from.
  # A general API like Vault will be best, but some other concrete implementations or a better (less popular) API may provide better performance in **some** case senarios.
  # The current list:
  # - LuckPerms
  # - Empty (This disables advanced chat formatting and instead uses normal chat formatting, you "may" use minimal chat formatting for channels, even normal chat.)
  # - Vault
  #
  # If you don't know what to choose, keep this at its current choice.
  # Vault can provide more generic support and compatibility, but if you can use a native chat/rank supplier such as LuckPerms, use it.
  #
  # Native options such as LuckPerms can provide better performance and *sometimes* more features (It depends on the option)
  chat-provider: "Empty"

  # MiniMessage is allowed.
  # Will not use legacy coloring.
  #
  # Chat format will be auto disabled as long as this is empty.
  group-format: ""

  placeholderapi: false

chat-cooldown:
  enabled: true

  # Order matters, whatever comes first in the list gets done first
  # How to use every default actions:
  #
  # Sound:
  # SOUND:<SoundType>:<Volume>:<Pitch>
  #
  # Action-bar:
  # ACTION_BAR:<Message>:[papi]
  #
  # Title:
  # TITLE:<Title>:<Subtitle>:<FadeIn>:<FadeOut>:<Stay>
  # The durations are in milliseconds, 1000 milliseconds equals 1 second :D
  on-chat-cooldown-actions:
    - "SOUND:UI_BUTTON_CLICK:1:1"
    - "ACTION_BAR:<gray>You are on cooldown!"

  # In seconds, may use decimals as milliseconds
  cooldown: 10

mentions:
  enabled: false

  # How to start a mention, such as @FlameyosFlow, #FlameyosFlow. if you don't want a mention symbol leave it blank at ""
  mention-symbol: ""
  mention-color: <gold><bold>

  # Order matters, whatever comes first in the list gets done first
  # How to use every default actions:
  #
  # Sound:
  # SOUND:<SoundType>:<Volume>:<Pitch>
  #
  # Action-bar:
  # ACTION_BAR:<Message>:[papi]
  #
  # Title:
  # TITLE:<Title>:<Subtitle>:<FadeIn>:<FadeOut>:<Stay>
  # The durations are in milliseconds, 1000 milliseconds equals 1 second :D
  on-mention-actions:
    - "SOUND:UI_BUTTON_CLICK:1:1"
    - "ACTION_BAR:<gray>You got mentioned by <bold><red>%player%"
    - "TITLE:<gray>You got mentioned by <bold><red>%player% (Title):Respond to Him (Subtitle):1:1:1"

# If you enable this or disable this, please restart the server for full stability :D
messaging:
  enabled: false

  count-message-other-as-conversation-end: true

  message-sender-format: "<gray>[<lightgray>You <gray>-> <lightgray>%recipient%<gray>]<lightgray>: <reset>%message%"

  message-recipient-format: "<gray>[<light_gray>%sender% <gray>-> <light_gray>You<gray>]<light_gray>: <reset>%message%"

# This is a pre-cached operation, it will only split once.
word-replacements: [ "wassup:hey" ]

enable-broadcasts: true

# Do not touch under any circumstances, this config file will be reset, and you will lose all the current edits you have made on this file.
# This is auto generated by BoostedYAML.
config-version: 1